- name: Found OS info
  debug:
   msg: "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"

- name: Check if OS var file exists
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "Linux.yml"
